apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: map_factions
    user: monitoring_user
    secureJsonData:
      password: monitoring_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false