server:
  port: "8080"
  environment: "development"
  read_timeout: "30s"
  write_timeout: "30s"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "map_factions"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  expiry: "24h"
  refresh_expiry: "168h"
  signing_method: "HS256"

external:
  mapbox_token: "pk.your-mapbox-token-here"
  mercado_pago_access_token: "your-mercado-pago-access-token"
  mercado_pago_public_key: "your-mercado-pago-public-key"